# PodPresent is pre defined configuration in which all pod 
# match the lables will inherits 

kind: PodPreset
apiVersion: settings.k8s.io/v1alpha1
metadata:
  name: allow-database
  namespace: default
spec:
  selector:
    matchLabels:
      role: frontend
  env:
    - name: DB_PORT
      value: "6379"
  volumeMounts:
    - mountPath: /cache
      name: cache-volume
  volumes:
    - name: cache-volume
      emptyDir: {}
---

apiVersion: v1
kind: Pod 
metadata:
   name: mypod
   labels:
     role: frontend
spec:
  containers:
  - name: mycontainer
    image: nginx 
    ports:
    - name: http 
      containerPort: 80
  

